- name: Run HTTPD
  docker_container:
    name: app-front
    image: sumpark/correction-tp1-devops:httpd
    pull: true
    recreate: true
    ports: "80:80"
    networks:
      - name: "app-network"

